name: Super-Linter

on:
  pull_request:

jobs:
  run-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          #  DISABLE STRICT CHECKS (IMPORTANT)
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false

          VALIDATE_HTML_PRETTIER: false